FROM postgres:13.1    
    


    #image: "postgres" # use latest official postgres version
    #environment:
    #  - POSTGRES_USER=root
    #  - POSTGRES_PASSWORD=root
    #  - POSTGRES_DB=database
    #ports:
    #  - 5432:5432
    #volumes:
    #  - ./database-data:/var/lib/postgresql/data/ # persist data even if container shuts down
#